(function(global){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
function grade(answers,questions,caseId=1){const correct=questions.map((q,i)=>Array.isArray(q.correct)?Array.isArray(answers[i])&&answers[i].length===q.correct.length&&q.correct.every(k=>answers[i].includes(k)):answers[i]===q.correct);const score=correct.filter(Boolean).length,core=({3:[2],4:[0,1],5:[0,3,4],6:[0,3,4]})[caseId]||[];return {correct,score,total:questions.length,rate:score/questions.length,grade:score===questions.length?'PERFECT':core.length?core.every(i=>correct[i])?'GOOD':'BAD':score>0?'GOOD':'BAD'};}
function newState(caseId=1,count=3){return {version:1,case:caseId,allRunEvidence:[],dayEvidence:[],screen:'title',day:0,first:null,second:null,route:null,location:'店内',done:[],runEvidence:[],answers:Array(count).fill(null),question:0,rescueUsed:false,result:null,queue:[],index:0,after:null,log:[],noticeShown:false};}
function newRecords(){return {version:1,unlocked:1,evidence:[],seen:[],characters:[],best:null,history:[]};}
function pointDone(s,r,key){return s.done.includes(key)||(!s.case||s.case===1)&&r.seen.includes(s.route+':'+key);}
function available(s,r,point){return point.requires.every(k=>pointDone(s,r,k));}
function ready(s,r,data){const route=data.routes[s.route];if(s.case>1)return !!route&&route.requiredEvidence.every(e=>(s.dayEvidence||[]).includes(e))&&(route.requiredPoints||[]).every(k=>s.done.includes(k));return !!route&&route.requiredEvidence.every(e=>route.points.some(p=>p.evidence.includes(e)&&pointDone(s,r,p.key)));}
function acquire(s,r,point){if(!s.done.includes(point.key))s.done.push(point.key);const id=s.route+':'+point.key;if(!r.seen.includes(id))r.seen.push(id);for(const e of s.case>1?[]:point.evidence){if(!s.runEvidence.includes(e))s.runEvidence.push(e);if(!r.evidence.includes(e))r.evidence.push(e);}return s;}
function finish(s,r){if(!s.result)throw Error('result missing');r.unlocked=Math.max(r.unlocked,Math.min(6,(s.case||1)+1));const ranks={BAD:0,GOOD:1,PERFECT:2};if(r.best===null||ranks[s.result.grade]>ranks[r.best])r.best=s.result.grade;for(const c of [s.first,s.second])if(!r.characters.includes(c))r.characters.push(c);r.history.push({date:new Date().toISOString(),case:s.case||1,choice:s.finalChoice??null,first:s.first,second:s.second,grade:s.result.grade,score:s.result.score});s.screen='result';return r;}
function verdict(s,r,data){const v=data.verdict;let q=[];if(s.result.grade==='PERFECT')q=[...v.perfect];else {const good=s.result.grade==='GOOD';q=[...(good?v.goodIntro:v.badIntro)];s.result.correct.forEach((ok,i)=>{if(!ok)q.push(...(good?v.goodQuestions[i]:v.badQuestions[i]));});q.push(...(good?v.goodEnd:v.badEnd),...v.cash);}if(data.case===1)q=q.filter(row=>![1103,1127].includes(row.row)||r.evidence.includes('E04'));q.push(...v.truth);return copy(q);}
const api={copy,grade,newState,newRecords,pointDone,available,ready,acquire,finish,verdict};if(typeof module!=='undefined')module.exports=api;global.ECLUNE_ENGINE=api;
})(typeof window==='undefined'?globalThis:window);
