// Headless JS/DOM simulation. Not a browser rendering test.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');const root=path.join(__dirname,'..');let checks=0;
function context(){const ids={},store=new Map(),timers=new Map();let timerID=0;store.set('bar-eclune-v01-settings',JSON.stringify({speed:0,bgm:0,se:0,voice:0}));function element(id=''){return ids[id]||(ids[id]={id,style:{setProperty(k,v){this[k]=v}},dataset:{},textContent:'',hidden:false,open:false,setAttribute(k,v){this[k]=v},tagName:'DIV',className:'',scrollHeight:100,querySelector:()=>element('modalbody'),querySelectorAll:()=>[],showModal(){this.open=true},close(){this.open=false},set innerHTML(v){this.html=v;for(const m of v.matchAll(/id="([^" ]+)"/g))element(m[1]);},get innerHTML(){return this.html||'';}});}const ctx={console,window:{ECLUNE_TEST:true,addEventListener(){},open(){}},document:{getElementById:element,activeElement:{tagName:'DIV'},addEventListener(){},createElement:()=>element('tmp')},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},Audio:class{constructor(src){this.src=src;this.volume=0}play(){return Promise.resolve()}pause(){}},setTimeout:(fn,ms)=>{const id=++timerID;timers.set(id,{fn,ms});return id},clearTimeout(id){timers.delete(id)},setInterval:()=>0,clearInterval(){},URL:{},Blob:class{},Date};ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['data.js','audio-manifest.js','voice-manifest.js','engine.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return {ctx,api:ctx.window.ECLUNE_TEST_API,store,ids,tick(ms){const t=[...timers].find(([id,t])=>t.ms===ms);assert(t,'scheduled delay '+ms);timers.delete(t[0]);t[1].fn();},timers};}
const check=(x,m)=>{assert(x,m);checks++;};function drain(a){let limit=1800;while(a.snapshot().screen==='dialogue'&&limit-->0)a.next();check(limit>0,'no dialogue loop');}
for(const f of ['紅','藍','翠'])for(const second of ['紅','藍','翠'].filter(c=>c!==f)){
 const {ctx,api:a,store,ids}=context();check(a.snapshot().screen==='title','title renders');a.act('start');drain(a);check(a.snapshot().screen==='select'&&a.snapshot().day===1,'prologue to selection');
 for(const c of [f,second]){
  a.act('choose:'+c);drain(a);check(a.snapshot().screen==='explore','route intro to investigation');let s=a.snapshot(),r=a.records(),route=ctx.window.ECLUNE_DATA.routes[s.route];
  a.act('return');drain(a);check(a.snapshot().screen==='explore','return blocked before mandatory');let todo=route.points.map(p=>p.key);for(let n=0;todo.length&&n<30;n++){let key=todo.find(k=>ctx.window.ECLUNE_ENGINE.available(a.snapshot(),a.records(),route.points.find(p=>p.key===k)));check(!!key,'point graph available');a.act('point:'+key);drain(a);todo=todo.filter(k=>k!==key);}
  check(!todo.length,'all points visited');const n=a.records().evidence.length;a.act('point:'+route.points[0].key);drain(a);check(a.records().evidence.length===n,'revisit no duplicate');a.act('return');check(ids.modal.open,'return confirmation');a.act('return-confirm');drain(a);
 }
 check(a.snapshot().screen==='reason'&&a.snapshot().day===3,'DAY3 to reasoning');for(let i=0;i<3;i++){a.act('question:'+i);a.act('answer:'+ctx.window.ECLUNE_DATA.questions[i].correct);}check(a.snapshot().result===null,'no early grading');a.act('confirm');a.act('submit');check(a.snapshot().rescueUsed&&a.snapshot().result===null,'rescue before grade');a.act('rescue-review');a.act('confirm');a.act('submit');drain(a);check(a.snapshot().screen==='result','ending to result');check(a.records().best==='PERFECT'&&a.records().unlocked===2,'persistent result');check(store.has('bar-eclune-v01-auto'),'autosave');a.act('save');a.act('saveslot:1');check(store.has('bar-eclune-v01-slot1'),'manual save');a.act('title');a.act('loadslot:1');check(a.snapshot().screen==='result','load restores');
}
// Red can return without finding the optional bag; no false found-money dialogue.
{const {api:a,ctx}=context();a.act('start');drain(a);a.act('choose:紅');drain(a);for(const k of ['register','envelope','window','door']){a.act('point:'+k);drain(a);}a.act('return-confirm');check(!a.snapshot().queue.some(r=>[285,293,299].includes(r.row)),'unfound cash lines gated');drain(a);a.act('choose:藍');check(!a.snapshot().queue.some(r=>[815,816].includes(r.row)),'DAY2 not assume cash found');}
// DAY2 keeps all actually visited DAY1 object/record points as safe reviews.
for(const first of ['紅','藍','翠'])for(const second of ['紅','藍','翠'].filter(c=>c!==first)){const {api:a,ctx,ids}=context();a.act('start');drain(a);a.act('choose:'+first);drain(a);const route=ctx.window.ECLUNE_DATA.routes[first];let todo=route.points.map(p=>p.key);while(todo.length){const k=todo.find(k=>ctx.window.ECLUNE_ENGINE.available(a.snapshot(),a.records(),route.points.find(p=>p.key===k)));a.act('point:'+k);drain(a);todo=todo.filter(x=>x!==k);}a.act('return-confirm');drain(a);a.act('choose:'+second);drain(a);const reviews=[...ids.main.innerHTML.matchAll(/data-action="point:(review-[^"]+)"/g)].map(m=>m[1]);check(reviews.length>0,'DAY2 has repeat investigation points '+first+second);const before=JSON.stringify({e:a.records().evidence,s:a.records().seen});for(const key of reviews){a.act('point:'+key);check(a.snapshot().queue.length>0,'review dialogue present');drain(a);}check(JSON.stringify({e:a.records().evidence,s:a.records().seen})===before,'reviews do not grant evidence or completion');}
// Every known speaker is visible even after more than three characters enter.
{const {api:a,ids,ctx}=context();a.act('start');let guard=1800;while(a.snapshot().screen==='dialogue'&&guard-->0){const s=a.snapshot(),row=s.queue[s.index];if(row.kind==='台詞'){for(const name of ['紅','藍','翠','宮本','男','俊介'])if(row.speaker===name)check(ids.portraits.innerHTML.includes('alt="'+name+'"')||(['宮本','男'].includes(name)&&/alt="(宮本|男)"/.test(ids.portraits.innerHTML)),'active speaker visible');}a.next();}a.act('menu');check(!ids['modal-inner'].innerHTML.includes('data-action="log"')&&!ids['modal-inner'].innerHTML.includes('data-action="records"'),'menu omits log and records');a.act('close');a.act('choose:紅');drain(a);a.act('point:register');check(ids.main.innerHTML.includes('clue-frame'),'evidence uses foreground frame');}
// UI regression checks: scene debut, modal export guard, and background clicks.
{const {api:a,ids,ctx}=context();a.act('start');check(!ids.portraits.innerHTML,'heading has no premature cast');while(a.snapshot().queue[a.snapshot().index].kind==='見出し')a.next();check(ids.main.innerHTML.includes('page-banner'),'location badge persists until next heading');let limit=50;while(!ids.portraits.innerHTML&&limit-->0)a.next();check(ids.portraits.innerHTML.includes('portrait-slot'),'first speaker reveals bust-up slot');check(a.snapshot().visibleCharacters.length<3,'not all characters revealed at start');const before=a.snapshot().index;ids.app.onclick({target:{closest:()=>null}});check(a.snapshot().index===before+1,'background advances once');const after=a.snapshot().index;ids.app.onclick({target:{closest:()=>true}});check(a.snapshot().index===after,'buttons do not advance');a.act('menu');check(ids['modal-inner'].innerHTML.includes('menu-grid'),'menu has two-column grid');a.act('export');check(ids['modal-inner'].innerHTML.includes('セーブデータをファイルで書き出しますか？'),'export asks first');check(ids['modal-inner'].innerHTML.includes('export-confirm'),'export requires explicit confirmation');ids.app.onclick({target:{closest:()=>null}});check(a.snapshot().index===after,'modal blocks advance');check(ids.footer.innerHTML.includes('この物語はフィクションです'),'fiction footer');a.act('close');a.act('cases');check(ids.main.className==='case-select','case viewport layout');check(ids.main.innerHTML.includes('case-media'),'unlocked fixed media wrapper');a.act('nextcase');check(ids.main.innerHTML.includes('case-media')&&ids.main.innerHTML.includes('case-locked'),'locked same wrapper');}
// Playback: prior-read only, stop at unread/modal/selection; AUTO advances once.
{const c=context(),{api:a,ids}=c;a.act('start');const i=a.snapshot().index;a.act('skip');check(a.playback()===null,'skip refuses new line');a.act('auto');check(a.playback()==='auto','auto toggles on');let delay=[...c.timers.values()].find(t=>t.ms>=1200&&t.ms<=6500&&t.ms!==2800);c.tick(delay.ms);check(a.snapshot().index===i+1,'AUTO advances line');a.next();check(a.playback()===null,'manual advance cancels AUTO');a.act('auto');a.act('menu');check(a.playback()===null,'menu cancels AUTO');a.act('close');drain(a);check(a.playback()===null,'selection stops playback');a.act('start');a.act('skip');check(a.playback()==='skip','previously read line can skip');c.tick(100);check(a.snapshot().index===1,'skip advances quickly');let guard=500;while(a.playback()==='skip'&&guard-->0)c.tick(100);check(guard>0&&a.playback()===null,'skip stops at unread or selection');check(a.snapshot().screen==='select','all read prologue reaches selection');a.act('choose:紅');a.act('skip');check(a.playback()===null,'skip stops before unvisited route');a.act('auto');ids.app.onclick({target:{closest:()=>null}});check(a.playback()===null,'screen click cancels playback');check(ids['auto-button']['aria-pressed']==='false','accessible toggle resets');}
console.log(JSON.stringify({passed:checks,mode:'Node DOM simulation',paths:6,browserVisualQA:false}));
