// Headless JS/DOM simulation. Not a browser rendering test.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');const root=path.join(__dirname,'..');let checks=0;
function context(){const ids={},store=new Map(),timers=new Map();let timerID=0;store.set('bar-eclune-v01-series',JSON.stringify({version:1,unlocked:6,cases:{}}));store.set('bar-eclune-v01-settings',JSON.stringify({speed:0,bgm:0,se:0,voice:0}));function element(id=''){return ids[id]||(ids[id]={id,style:{setProperty(k,v){this[k]=v}},dataset:{},textContent:'',hidden:false,open:false,setAttribute(k,v){this[k]=v},tagName:'DIV',className:'',scrollHeight:100,querySelector:()=>element('modalbody'),querySelectorAll:()=>[],showModal(){this.open=true},close(){this.open=false},set innerHTML(v){this.html=v;for(const m of v.matchAll(/id="([^" ]+)"/g))element(m[1]);},get innerHTML(){return this.html||'';}});}const ctx={console,window:{ECLUNE_TEST:true,addEventListener(){},open(){}},document:{getElementById:element,activeElement:{tagName:'DIV'},addEventListener(){},createElement:()=>element('tmp')},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},Audio:class{constructor(src){this.src=src;this.volume=0}play(){return Promise.resolve()}pause(){}},setTimeout:(fn,ms)=>{const id=++timerID;timers.set(id,{fn,ms});return id},clearTimeout(id){timers.delete(id)},setInterval:()=>0,clearInterval(){},URL:{},Blob:class{},Date};ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['data.js','series.js','audio-manifest.js','voice-manifest.js','engine.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});return {ctx,api:ctx.window.ECLUNE_TEST_API,store,ids,tick(ms){const t=[...timers].find(([id,t])=>t.ms===ms);assert(t,'scheduled delay '+ms);timers.delete(t[0]);t[1].fn();},timers};}

const check=(v,m)=>{assert(v,m);checks++;};
function drain(a){let limit=10000;while(a.position().screen==='dialogue'&&limit-->0)a.next();check(limit>0,'dialogue ends');}
function routePlay(c,first,second,answers=null,choice=1,optional=true){console.log('route',c,first,second,optional?'all':'required');const h=context(),{api:a,ctx,ids}=h;const data=ctx.window.ECLUNE_CASES[c];a.act('case:'+(c-1));a.act('start');drain(a);check(a.snapshot().screen==='select','initial picker '+c);
for(const char of [first,second]){a.act('choose:'+char);drain(a);check(a.snapshot().screen==='explore','explore '+c+char);const route=data.routes[a.snapshot().route];a.act('return-confirm');check(a.snapshot().screen==='dialogue'||ids.modal?.open||ids.toast?.textContent,'early return rejected');if(a.snapshot().screen==='dialogue')drain(a);a.act('close');let todo=route.points.filter(p=>optional||!p.optional).map(p=>p.key);let guard=100;while(todo.length&&guard-->0){const s=a.snapshot();const p=route.points.find(p=>todo.includes(p.key)&&ctx.window.ECLUNE_ENGINE.available(s,a.records(),p));check(!!p,'available point '+c+first+second+' '+todo);a.act('location:'+p.location);a.act('point:'+p.key);drain(a);check(a.snapshot().screen==='explore','returns to investigation');todo=todo.filter(k=>k!==p.key);}check(!todo.length,'all selected points finish');check(ctx.window.ECLUNE_ENGINE.ready(a.snapshot(),a.records(),data),'all mandatory facts confirmed '+c+first+second);a.act('return');check(ids.modal.open,'return asks');a.act('return-confirm');drain(a);}
check(a.snapshot().screen==='reason','reason '+c);const target=answers||data.questions.map(q=>q.correct);for(let i=0;i<data.questions.length;i++){if(c===6&&i===4){const saved=JSON.stringify(a.snapshot().answers.slice(0,4));a.act('additional');drain(a);check(a.snapshot().day===4&&a.snapshot().screen==='reason','DAY4 final reason');check(JSON.stringify(a.snapshot().answers.slice(0,4))===saved,'first four answers retained');check(a.snapshot().allRunEvidence.includes('E90'),'DAY4 confirms E90');}a.act('question:'+i);for(const value of Array.isArray(target[i])?target[i]:[target[i]])a.act('answer:'+value);}
a.act('confirm');check(a.snapshot().screen==='confirm','confirmation');a.act('submit');a.act('grade');drain(a);if(c===3){check(a.snapshot().screen==='final-choice','ungraded decision after truth');const grade=a.snapshot().result.grade;a.act('final-choice:'+choice);drain(a);check(a.snapshot().result.grade===grade,'decision does not change grade');check(a.records().history.at(-1).choice===choice,'decision saved');}
check(a.snapshot().screen==='result','clear '+c+first+second);check(a.records().best===ctx.window.ECLUNE_ENGINE.grade(target,data.questions,c).grade,'case-specific grading');check(!ids.main.innerHTML.includes('Xで共有')||c===6,'share final only');a.act('save');a.act('saveslot:1');a.act('title');a.act('loadslot:1');check(a.snapshot().screen==='result'&&a.snapshot().case===c,'case-aware save restores');return h;}
for(let c=1;c<=6;c++)for(const first of ['紅','藍','翠'])for(const second of ['紅','藍','翠'].filter(x=>x!==first))routePlay(c,first,second);
// Optional evidence must not block any of the 36 combinations.
for(let c=1;c<=6;c++)for(const first of ['紅','藍','翠'])for(const second of ['紅','藍','翠'].filter(x=>x!==first))routePlay(c,first,second,null,0,false);
// Grade rules across every correctness pattern, including exact multi-select sets.
{const {ctx}=context(),E=ctx.window.ECLUNE_ENGINE;for(let c=1;c<=6;c++){const d=ctx.window.ECLUNE_CASES[c],n=d.questions.length;for(let mask=0;mask<(1<<n);mask++){const correct=d.questions.map((q,i)=>!!(mask&(1<<i))),answers=d.questions.map((q,i)=>correct[i]?q.correct:Array.isArray(q.correct)?[q.options.length-1]:(q.correct+1)%q.options.length),grade=E.grade(answers,d.questions,c);const core=({3:[2],4:[0,1],5:[0,3,4],6:[0,3,4]})[c]||[];const expected=correct.every(Boolean)?'PERFECT':core.length?core.every(i=>correct[i])?'GOOD':'BAD':correct.some(Boolean)?'GOOD':'BAD';check(grade.grade===expected,'grade mask '+c+mask);const state=E.newState(c,n);state.answers=answers;state.result=grade;const verdict=E.verdict(state,E.newRecords(),d);for(let q=0;q<n;q++){const line=(expected==='BAD'?d.verdict.badQuestions:d.verdict.goodQuestions)[q]?.find(r=>r.kind==='UI'&&r.text.startsWith('不正解'));if(line)check(verdict.some(r=>r.id===line.id)===(!correct[q]&&expected!=='PERFECT'),'wrong answers only '+c+q);}}
for(const q of d.questions.filter(q=>q.multi))for(let mask=0;mask<(1<<q.options.length);mask++){const values=q.options.map((_,i)=>i).filter(i=>mask&(1<<i));check(E.grade([values],[q],1).correct[0]===(values.length===q.correct.length&&q.correct.every(i=>values.includes(i))),'exact multi-selection');}}}
// Exercise non-perfect full endings and both ungraded decision branches.
for(let c=2;c<=6;c++){const {ctx}=context(),d=ctx.window.ECLUNE_CASES[c],core=({3:[2],4:[0,1],5:[0,3,4],6:[0,3,4]})[c]||[0];const good=d.questions.map((q,i)=>core.includes(i)?q.correct:Array.isArray(q.correct)?[q.options.length-1]:(q.correct+1)%q.options.length);routePlay(c,'紅','藍',good,0,false);const bad=d.questions.map(q=>Array.isArray(q.correct)?[q.options.length-1]:(q.correct+1)%q.options.length);routePlay(c,'紅','翠',bad,1,false);}
// Source text is retained; conditional facts use this run, never replay history.
{const {ctx}=context();for(let c=2;c<=6;c++){const d=ctx.window.ECLUNE_CASES[c],source=new Map(d.rows.map(r=>[r.id,r.text]));const visit=x=>{if(Array.isArray(x))x.forEach(visit);else if(x&&typeof x==='object'){if(x.id&&x.text!==undefined)check(source.get(x.id)===x.text,'FIX text '+x.id);Object.values(x).forEach(visit);}};for(const key of ['prologue','routes','day3Intro','verdict','finalChoice','additionalIntro','additional','day4'])visit(d[key]);}}
console.log(JSON.stringify({passed:checks,cases:6,paths:72,browserVisualQA:false}));
